spring:
  application:
    name: Ticket_backend
  datasource:
    username: ticket
    password: ticket
    url: jdbc:postgresql://localhost:5432/ticket
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect